title: "Mouse Potato Does Stuff"
email: dorijan.cirkveni@engineer.com
description: "Just me talking about tech and stuff, idk"
baseurl: ""
url: ""
twitter_username: MouseDoes
github_username:  Dorijan-Cirkveni

theme: minima
plugins:
  - jekyll-feed

# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
